CREATE DATABASE ReciclaDB;
USE ReciclaDB;

CREATE TABLE UsuarioCPF (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CPF VARCHAR(11) NOT NULL UNIQUE,
    Nome VARCHAR(100) NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL,
    Telefone VARCHAR(15),
    SenhaHash VARCHAR(255) NOT NULL,
    DataCadastro DATETIME DEFAULT CURRENT_TIMESTAMP,
    Pontos INT DEFAULT 0
);

CREATE TABLE UsuarioCNPJ (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CNPJ VARCHAR(14) NOT NULL UNIQUE,
    RazaoSocial VARCHAR(100) NOT NULL,
    NomeFantasia VARCHAR(100) NOT NULL,
    InscricaoEstadual VARCHAR(20),
    Email VARCHAR(100) UNIQUE NOT NULL,
    Telefone VARCHAR(15),
    SenhaHash VARCHAR(255) NOT NULL,
    DataCadastro DATETIME DEFAULT CURRENT_TIMESTAMP,
    Endereco_ID INT,
    FOREIGN KEY (Endereco_ID) REFERENCES Endereco(ID)
);

CREATE TABLE Endereco (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Rua VARCHAR(100) NOT NULL,
    Numero VARCHAR(10) NOT NULL,
    Complemento VARCHAR(50),
    Bairro VARCHAR(50) NOT NULL,
    Cidade VARCHAR(50) NOT NULL,
    Estado VARCHAR(2) NOT NULL,
    CEP VARCHAR(8) NOT NULL
);

CREATE TABLE Produto (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    Descricao TEXT,
    PontosPorUnidade INT NOT NULL,
    Estoque INT DEFAULT 0
);

CREATE TABLE OfertaProduto (
    Produto_ID INT NOT NULL,
    UsuarioCNPJ_ID INT NOT NULL,
    ValorPontos INT NOT NULL,
    FOREIGN KEY (Produto_ID) REFERENCES Produto(ID),
    FOREIGN KEY (UsuarioCNPJ_ID) REFERENCES UsuarioCNPJ(ID)
);

CREATE TABLE ResgateProduto (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    UsuarioCPF_ID INT NOT NULL,
    Produto_ID INT NOT NULL,
    DataResgate DATETIME DEFAULT CURRENT_TIMESTAMP,
    PontosGastos INT NOT NULL,
    StatusResgate VARCHAR(20),
    FOREIGN KEY (UsuarioCPF_ID) REFERENCES UsuarioCPF(ID),
    FOREIGN KEY (Produto_ID) REFERENCES Produto(ID)
);

CREATE TABLE RecebePontos (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    UsuarioCPF_ID INT NOT NULL,
    UsuarioCNPJ_ID INT NOT NULL,
    DataRecebimento DATETIME DEFAULT CURRENT_TIMESTAMP,
    PontosRecebidos INT NOT NULL,
    Descricao VARCHAR(100),
    FOREIGN KEY (UsuarioCPF_ID) REFERENCES UsuarioCPF(ID),
    FOREIGN KEY (UsuarioCNPJ_ID) REFERENCES UsuarioCNPJ(ID)
);

CREATE TABLE RecuperacaoSenha (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    UsuarioCNPJ_ID INT,
    UsuarioCPF_ID INT,
    Token VARCHAR(255) NOT NULL,
    DataCriacao DATETIME DEFAULT CURRENT_TIMESTAMP,
    Expiracao DATETIME NOT NULL,
    IsUsed BOOLEAN NOT NULL DEFAULT 0,
    FOREIGN KEY (UsuarioCNPJ_ID) REFERENCES UsuarioCNPJ(ID),
    FOREIGN KEY (UsuarioCPF_ID) REFERENCES UsuarioCPF(ID)
);